apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      masSurge: 40%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine3.20-slim
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
              name: app-ts
            - secretRef:
              name: app-ts-secrets
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

